#TODO create-service: rename file
version: '3'

services:
  service:
    #TODO create-service: rename
    image: demo-service:latest
    ports:
      - 8080:8080
    environment:
      - S_POSTGRES_HOST=postgres
      - S_KAFKA_BOOTSTRAP_HOST=kafka:9092
    depends_on:
      - kafka
      - postgres